### ISSUE TITLE
例題との変化

### ISSUE THREAD

**Issue by c0b21025dc** [c0b210191a/ProjExD#10]
https://github.com/c0b210191a/ProjExD/blob/ab299f4e53be42c0616ed1d9f433e085e17635c3/ex03/maze.py#L39

処理速度の問題があるとは思わなかった

**Comment by c0b210191a** [comment]
数値の違いで秒数が変わるので、1000より100のほうが良いと考えました

**Comment by c0b210191a** [comment]
修正しました
少し数値を変えました
